### ISSUE TITLE
我部署linux 环境的出现了问题 希望大神帮我看下 。这个so 文件到底是为什么会缺少 ？

### ISSUE THREAD

**Issue by Tangjinquan** [ww23/BlindWaterMark#12]
`[2020-07-20 17:41:40.413] [main] [ERROR] [c.b.p.m.l.e.GlobalUncaughtExceptionHandler] [TID:N/A] - An exception has been raised by Name:main,Id:1,Class:class java.lang.Thread
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.UnsatisfiedLinkError: no jniopencv_highgui in java.library.path: [/usr/local/lib64, /usr/local/lib, /usr/lib64, /usr/lib, /lib64, /lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2654)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:876)
	at java.base/java.lang.System.loadLibrary(System.java:1875)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1543)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1192)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1042)
	at org.bytedeco.opencv.global.opencv_highgui.<clinit>(opencv_highgui.java:22)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1109)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1058)
	... 8 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/opencv-4.1.2-1.5.2-linux-x86_64.jar/org/bytedeco/opencv/linux-x86_64/libjniopencv_highgui.so: /usr/lib64/libpango-1.0.so.0: undefined symbol: fribidi_get_par_embedding_levels_ex
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2424)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2481)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2678)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2611)
	at java.base/java.lang.Runtime.load0(Runtime.java:814)
	at java.base/java.lang.System.load(System.java:1838)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1493)
	... 16 common frames omitted`

**Comment by Tangjinquan** [comment]
上面的问题是我执行了
 yum groupinstall "Development Tools"
yum install gtk+-devel gtk2-devel　　
这两个命令之后 启动项目报的错 。
在这之前我报的错就是 缺少 gtk

**Comment by ww23** [comment]
尝试这个 issue 的解决方案 [javacv #422](https://github.com/bytedeco/javacv/issues/422)

**Comment by Tangjinquan** [comment]
我解决了问题，原因是因为跟我在linux 编译部署的ffmpeg有关系 ，ffmpeg 生成的so 文件和 opncv的so文件有冲突 。导致不能识别
