### ISSUE TITLE
当使用DCT方式且图片的宽高有奇数的时候会报错

### ISSUE THREAD

**Issue by okavatar** [ww23/BlindWaterMark#6]
`
Exception in thread "main" java.lang.RuntimeException: OpenCV(3.4.2) C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.4.2\modules\core\src\dxt.cpp:4149: error: (-213:The function/fe
ature is not implemented) Odd-size DCT's are not implemented in function 'cv::OcvDctImpl::apply'

        at org.bytedeco.javacpp.opencv_core.dct(Native Method)
        at me.ww23.image.BlindWatermark.startDCT(BlindWatermark.java:254)
        at me.ww23.image.BlindWatermark.decodeDCT(BlindWatermark.java:186)
        at me.ww23.image.BlindWatermark.main(BlindWatermark.java:64)
`
麻烦大佬看看谢谢

**Comment by okavatar** [comment]
是不是可以去掉一根1像素的线进行运算，算完了再把这根线补回去输出图像。

**Comment by ww23** [comment]
反过来应该比较好，先补一像素，加完水印再去掉，不会丢失一像素的信息。


okavatar <notifications@github.com> 于2019年1月11日周五 上午11:03写道：

**Comment by Jimmy6l** [comment]
楼主解决了吗
